### ISSUE TITLE
How does Mutable Security works?

### ISSUE THREAD

**Issue by iosifnicolae2** [MutableSecurity/mutablesecurity#26]
### Question

How does Mutable Security works?
Do you plan on supporting Kubernetes cluster monitoring?

### Contact Details

iosif@bringes.io

**Comment by iosifache** [comment]
Hi, @iosifnicolae2.

> How does Mutable Security works?

MutableSecurity is currently a CLI tool that IT/security administrators, DevSecOps engineers, and blue teamers can install on self-managed servers via PyPi (`pip install mutablesecurity`). We support the cybersecurity solutions suite throughout its entire lifecycle, from installation (`--operation INSTALL`) and configuration (`--operation SET_CONFIGURATION`) to upgrade (`--operation UPGRADE`) and statistics retrieval (`--operation GET_STATS`).

For the coming weeks, we also plan to extend our solution with a web user interface to monitor the installed solutions through tests and metrics.

> Do you plan on supporting Kubernetes cluster monitoring?

Our efforts were previously focused on solutions that can be installed on self-managed servers (for example, intrusion detection and prevention systems, antivirus programs and backup solutions). However, if there will be feature requests for K8S security solutions, we will work on them!
